name: 爬虫定时任务
on:
  schedule:
  - cron: 0 16 * * *
  workflow_dispatch:
jobs:
  build:
    name: 爬虫定时任务
    container:
      image: jadehh/ubuntu:spider-1.0.0
      options: --shm-size=2gb
    runs-on: ${{ matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest" ] #, "macos-latest", "windows-latest"
    steps:
      - name: 下载代码
        uses: actions/checkout@v3
        with:
          repository: jadehh/Spider
          ref: main
          path: code
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
      - name: 安装pip环境
        run: |
          pip install -r code/requirements.txt
      - name: 执行爬虫脚本
        run: |
          cd code
          python test.py

      - name: 上传爬虫json文件
        run: |
          cd code
          git checkout main
          git config --global user.email "jadehh@live.com"
          git config --global user.name "jade"
          ls -l
#          cp code/json/xiaozhitiao.json
#          git add json/xiaozhitiao.json
#          commit_msg="*  更新小纸条爬虫结果"
#          git commit -a -m "$commit_msg"
      
#      - name: 查看当前分支信息
#        run: |
#          ls -l
#      - name: 上传分支
#        uses: ad-m/github-push-action@master
#        with:
#          github_token: ${{ secrets.GH_PAT }}
#          repository: jadehh/Spider
#          directory: .
#          branch: main
#          force: true
#          tags: true
#        env:
#          GITHUB_ACTOR: jadehh
